use_frameworks!

platform :ios, '9.0'

target 'MJKNetworking_Example' do
  pod 'MJKNetworking', :path => '../'

  target 'MJKNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
